config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'

  get '/users/sign_up', to: 'registrations#new', as:'registration'
  post '/users', to: 'registrations#create'

  get '/users/sign_in', to: 'sessions#new', as:'session'


  post '/login', to: 'sessions#create', as:'login'

  delete '/users/sign_out', to:'session#destroy', as: 'logout'

  resources :boards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    validates :title,presence:true,length: {minimum:4}
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true,
                  uniqueness: true,
                  format: { with: /[\w]+@([\w-]+\.)+[\w-]{2,4}/ }

  validates :password, presence: true,
                       confirmation: true,
                       length: { minimum: 4 }


  validates :nickname, presence: true

  before_create :encrypt_password

  def self.login(user)
    pw = Digest::SHA1.hexdigest("a#{u[:password]}z")
    User.find_by(email:user[:email], password: pw )

  end

  private
  def encrypt_password
    self.password = Digest::SHA1.hexdigest("a#{self.password}z")
  end
end

# SHA1加密

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private
  def record_not_found
    render file: 'public/404.html',
           layout: false,
           status: :not_found
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :find_board, only: [:show, :edit, :update, :destroy]
# except:[:index, :new, :creat]


    def index
        @boards = Board.all
        # Board.where(id: 3) 會找出預設值11筆資料
    end
    
    def show
        # find會顯示錯誤 find_by會顯示 nil   
        # @board = Board.find(params[:id])
        # find_board
        # Board.find(1)
        # Board.find_by(id: 1) 可組多個變數
        # Board.find_by(email: 'aaa')
        # Board.find_by(id: 2, email: 'aaa')
    end

    def new
        @board = Board.new
    end


    def create
        # p params["board"]
    # params["board"] -> { "title" => 'ccc' }
    # clean_params = params.require(:board).permit(:title)
    @board = Board.new(board_params)
        # @boards = Board.new
        # @boards = Board.new(params["board"])
    if @board.save
            # flash["notice"] = "成功新增看板"
            # 成功
        redirect_to "/", notice:'成功新增看板'
     else
            # 失敗
     render :new 
         # render 'boards/new'
        # 資料會重洗 會重打全部
          end

     end


     def update
        # @board = Board.find(params[:id])
        # find_board
        # clean_params = params.require(:board).permit(:title)
        if @board.update(board_params)
            redirect_to root_path, notice: '更新成功'
        else
            render:edit
        end
     end

     def edit
        # @board = Board.find(params[:id])
        # find_board
     end

     def destroy
        # @board = Board.find(params[:id])
        # find_board
        @board.destroy
        redirect_to root_path, notice: '看板已刪除'
     end

     def find_board
        @board = Board.find(params[:id])
     end

     def board_params
        clean_params = params.require(:board).permit(:title)
      end

end 
 

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def sign_up
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save

      redirect_to root_path ,notice: 'ok' 
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password,:paddword_confirmation, :nickname)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def create  
        if User.login(params[:user])
            session[:user9527] = params[:user][:mail]
            redirect_to root_path, notice:'登入成功'
        else
            redirect_to session_path, notice:'登入失敗'
        end
    end

    def destroy
        session[:user9527] = nil
        redirect_to root_path, notice: '已登出'
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/session_helper.rb
module SessionsHelper
    def current_user
        User.find_by(email: session[:user9527])
    end
end

app/views/boards/_form.html.erb
<% if board.errors.any? %>
  <ul>
    <% board.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(board) do |form| %>
  <%= form.label :title, '看板標題' %>
  <%= form.text_field :title %>
  <%= form.submit %>
<% end %>

app/views/boards/edit.html.erb
<h1>編輯看板</h1>
<h1><%= @board.title %> </h1>

<%= render 'form' , board: @board %>

app/views/boards/index.html.erb
<h1>看板列表</h1>

<%# <a href="/boards/new">新增看板</a>
<%# <a href ="<%= new_board_path %>
<%# >新增看板1</a> %> 
<%# new board path 可以改 全部路徑 routs + path:'boards %>
<%# <%= link_to "新增看板", '/boards/new' %> 
<%= link_to "新增看板", new_board_path %> 
<%# 第八行 最推薦寫法 name routes %>
<%# view hepler  %>

<%# data-confirm %>

<ul>
<% @boards.each do |board| %>
  <li>
    <%= link_to "編輯", edit_board_path(board.id) %>
     <%= link_to "刪除", board_path(board.id),method: 'delete',
     data: {confirm: '是否確定刪除?'}  %>
    <%= link_to board.title, board_path(board.id) %>
  </li>
<% end %>
</ul>

app/views/boards/new.html.erb
<h1>新增看板</h1>

<%# <form action="/boards" method="post">
<button type="submit">送出</button>
</form> %>



<%= render 'form', board: @board %>




<!-- 
<%# emmet.includeLanguages": {
    "erb".html,
    "aaa:".html, %>

<%# new -> create  慣例
    edit -> update %> -->

   

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZCard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/navbar" %>
 <%# partial render %>
  <%= render "shared/notice" if flash[:notice] %>
  <section class="main-section">
    <%= yield %>
    </section>
  </body>
</html>

app/views/session/new.html.erb
<h1>會員登入</h1>


<% form_with(model:@user,url:login_path, method: 'post',local:true ) do |form|%>

<div class="fields">
    <%= form.label :email '帳號'%>
    <%= form.text_field :email %>
    
  </div>

    <div class="fields">
    <%= form.label :password, '密碼' %>
    <%= form.password_field :password %>
  </div>


  <%= form.submit '登入' %>
  <% end %>

app/views/shared/_flash.html.erb
<p><%= flash ["notice"] %></p>

app/views/shared/_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to "首頁", root_path %></li>
    <li><%= link_to "看板列表", boards_path %></li>
  </ul>

  <ul>
  <% if current_user %>
  <li><%= current_user  %></li>
  <li><%= link_to '登出', logout_path,method: 'delete' %></li>
  <% else %>

    <li><%= link_to "註冊", registration_path %></li>
    <li><%= link_to "登入",  session_path %></li>
    <% end %>
  </ul>
</nav>